apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pxl
  template:
    metadata:
      labels:
        app: pxl
    spec:
      containers:
        - name: pxl
          image: freddo256/pxl:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000